In [2]:
import torch
import torch.nn.functional as F
from torch import nn

In [14]:
import tiktoken
enc = tiktoken.get_encoding('gpt2')
enc.n_vocab
enc.decode(enc.encode('REG is a cool place to work'))

'REG is a cool place to work'

In [3]:
import torch

# create two tensors of shape [3, 3]
tensor_a = torch.randn(3, 3)
tensor_b = torch.randn(3, 3)

print("Tensor A: \n", tensor_a)
print("Tensor B: \n", tensor_b)

Tensor A: 
 tensor([[-1.2444,  1.8189, -0.2863],
        [ 1.1675, -0.6728, -0.2610],
        [ 0.1087,  1.6304,  1.6097]])
Tensor B: 
 tensor([[ 0.9061,  0.0605, -0.0354],
        [-0.8794, -1.3505, -0.0227],
        [-0.5416,  0.6573,  0.3468]])


In [5]:
list(set('abdhfje'))

['b', 'd', 'a', 'j', 'e', 'h', 'f']

In [3]:
# concatenate along the 0th (vertical) dimension
concat_0 = torch.cat([tensor_a, tensor_b], dim=0)
print("Concatenate along 0th dimension: \n", concat_0)
print("Shape of concat_0: ", concat_0.shape)

Concatenate along 0th dimension: 
 tensor([[-1.1492, -0.0582,  0.3424],
        [-0.9320, -0.6149, -0.5130],
        [-0.5966, -1.4858, -0.9528],
        [-1.0260, -0.3455, -0.2561],
        [-2.0339, -1.1503,  1.1568],
        [-0.7132, -2.3608,  0.4777]])
Shape of concat_0:  torch.Size([6, 3])


In [4]:
# concatenate along the 1st (horizontal) dimension
concat_1 = torch.cat([tensor_a, tensor_b], dim=1)
print("Concatenate along 1st dimension: \n", concat_1)
print("Shape of concat_1: ", concat_1.shape)

Concatenate along 1st dimension: 
 tensor([[-1.1492, -0.0582,  0.3424, -1.0260, -0.3455, -0.2561],
        [-0.9320, -0.6149, -0.5130, -2.0339, -1.1503,  1.1568],
        [-0.5966, -1.4858, -0.9528, -0.7132, -2.3608,  0.4777]])
Shape of concat_1:  torch.Size([3, 6])


In [9]:
# stack along a new dimension
stack_0 = torch.stack([tensor_a, tensor_b], dim=0)
print("Stack along a new dimension: \n", stack_0)
print("Shape of stack_0: ", stack_0.shape)

Stack along a new dimension: 
 tensor([[[-1.1492, -0.0582,  0.3424],
         [-0.9320, -0.6149, -0.5130],
         [-0.5966, -1.4858, -0.9528]],

        [[-1.0260, -0.3455, -0.2561],
         [-2.0339, -1.1503,  1.1568],
         [-0.7132, -2.3608,  0.4777]]])
Shape of stack_0:  torch.Size([2, 3, 3])


In [54]:
k = torch.randn(B, T, head_size)
q = torch.randn(B, T, head_size)
wei = q @ k.transpose(-2, -1) * head_size ** -0.5
wei.var()

tensor(0.7552)

In [71]:
F.softmax(torch.tensor([0.4, 0.2, 0.3, 0.5]), dim=-1)
F.softmax(torch.tensor([0.4, 0.2, 0.3, 0.5])*16, dim=-1)


tensor([0.1614, 0.0066, 0.0326, 0.7994])

In [41]:
B, T, C = 4, 8, 32 # Batch, Time, Channel
x = torch.randn(B, T, C) 

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
v = value(x)

wei = q @ k.transpose(-2, -1) * head_size ** -0.5

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril==0, float('-inf'))
wei = F.softmax(wei, dim = -1)
xbow = wei @ v
xbow.var()

tensor(0.1193, grad_fn=<VarBackward0>)

In [49]:
out.var()

tensor(0.1659, grad_fn=<VarBackward0>)